[project]
name = "source-digestion-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "EliasSchlie", email = "EliasSchlie@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.27",
    "langchain-core>=0.3.74",
    "langchain-openai>=0.3.30",
    "langgraph>=0.6.5",
    "mlflow>=3.3.0",
]

[project.scripts]
source-digestion-agent = "source_digestion_agent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
