[project]
name = "source-digestion-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "EliasSchlie", email = "EliasSchlie@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
source-digestion-agent = "source_digestion_agent:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
